export default [
  [
    { type: 'fkey', name: 'Esc', keycode: 27, width: 60 },
    { type: 'symbol', symbol: '`~ёЁ', keycode: 192, caps: true },
    { type: 'number', symbol: '1!1!', keycode: 49 },
    { type: 'number', symbol: '2@2"', keycode: 50 },
    { type: 'number', symbol: '3#3№', keycode: 51 },
    { type: 'number', symbol: '4$4;', keycode: 52 },
    { type: 'number', symbol: '5%5%', keycode: 53 },
    { type: 'number', symbol: '6^6:', keycode: 54 },
    { type: 'number', symbol: '7&7?', keycode: 55 },
    { type: 'number', symbol: '8*8*', keycode: 56 },
    { type: 'number', symbol: '9(9(', keycode: 57 },
    { type: 'number', symbol: '0)0)', keycode: 48 },
    { type: 'number', symbol: '-_-_', keycode: 189 },
    { type: 'number', symbol: '=+=+', keycode: 187 },
    { type: 'fkey', icon: 'backspace', keycode: 8, width: 120 },
  ],
  [
    { type: 'fkey', keycode: 9, name: 'Tab', width: 90 },
    { type: 'symbol', symbol: 'qQйЙ', keycode: 81, caps: true },
    { type: 'symbol', symbol: 'wWцЦ', keycode: 87, caps: true },
    { type: 'symbol', symbol: 'eEуУ', keycode: 69, caps: true },
    { type: 'symbol', symbol: 'rRкК', keycode: 82, caps: true },
    { type: 'symbol', symbol: 'tTеЕ', keycode: 84, caps: true },
    { type: 'symbol', symbol: 'yYнН', keycode: 89, caps: true },
    { type: 'symbol', symbol: 'uUгГ', keycode: 85, caps: true },
    { type: 'symbol', symbol: 'iIшШ', keycode: 73, caps: true },
    { type: 'symbol', symbol: 'oOщЩ', keycode: 79, caps: true },
    { type: 'symbol', symbol: 'pPзЗ', keycode: 80, caps: true },
    { type: 'symbol', symbol: '[{хХ', keycode: 219, caps: true },
    { type: 'symbol', symbol: ']}ъЪ', keycode: 221, caps: true },
    { type: 'symbol', symbol: '\\|\\|', keycode: 220 },
    { type: 'fkey', name: 'Del', keycode: 46, width: 60 },
  ],
  [
    { type: 'fkey', name: 'Caps', keycode: 20, width: 120 },
    { type: 'symbol', symbol: 'aAфФ', keycode: 65, caps: true },
    { type: 'symbol', symbol: 'sSыЫ', keycode: 83, caps: true },
    { type: 'symbol', symbol: 'dDвВ', keycode: 68, caps: true },
    { type: 'symbol', symbol: 'fFаА', keycode: 70, caps: true },
    { type: 'symbol', symbol: 'gGпП', keycode: 71, caps: true },
    { type: 'symbol', symbol: 'hHрР', keycode: 72, caps: true },
    { type: 'symbol', symbol: 'jJоО', keycode: 74, caps: true },
    { type: 'symbol', symbol: 'kKлЛ', keycode: 75, caps: true },
    { type: 'symbol', symbol: 'lLдД', keycode: 76, caps: true },
    { type: 'symbol', symbol: ';:жЖ', keycode: 186, caps: true },
    { type: 'symbol', symbol: '\'"эЭ', keycode: 222, caps: true },
    { type: 'fkey', name: 'Enter', keycode: 13, width: 120.5 },
  ],
  [
    { type: 'fkey', name: 'Shift', keycode: 16, width: 150 },
    { type: 'symbol', symbol: 'zZяЯ', keycode: 90, caps: true },
    { type: 'symbol', symbol: 'xXчЧ', keycode: 88, caps: true },
    { type: 'symbol', symbol: 'cCсС', keycode: 67, caps: true },
    { type: 'symbol', symbol: 'vVмМ', keycode: 86, caps: true },
    { type: 'symbol', symbol: 'bBиИ', keycode: 66, caps: true },
    { type: 'symbol', symbol: 'nNтТ', keycode: 78, caps: true },
    { type: 'symbol', symbol: 'mMьЬ', keycode: 77, caps: true },
    { type: 'symbol', symbol: ',<бБ', keycode: 188, caps: true },
    { type: 'symbol', symbol: '.>юЮ', keycode: 190, caps: true },
    { type: 'symbol', symbol: '/?.,', keycode: 191 },
    { type: 'fkey', icon: 'arrow-up', keycode: 38, width: 60 },
    { type: 'fkey', name: 'Shift', keycode: 16, width: 121 },
  ],
  [
    { type: 'fkey', name: 'Ctrl', keycode: 17, width: 100 },
    { type: 'fkey', name: 'Alt', keycode: 18, width: 80 },
    { type: 'fkey', name: ['en', 'EN', 'ru', 'RU'], width: 60 },
    { type: 'symbol', symbol: '    ', keycode: 32 },
    { type: 'fkey', icon: 'arrow-left', keycode: 37, width: 60 },
    { type: 'fkey', icon: 'arrow-down', keycode: 40, width: 60 },
    { type: 'fkey', icon: 'arrow-right', keycode: 39, width: 60 },
    { type: 'fkey', name: 'End', keycode: 35, width: 58 },
  ],
];
